/**
 * Image-generation error contract — shared by every image adapter
 * (`src/llm/venice.ts` today; fal/oai via the AI SDK + the tool
 * handler's APICallError conversion) and consumed by the agent-side
 * tool handler.
 *
 * Lives in `src/llm/` because providers throw into this vocabulary;
 * the post-generation inspector (`detectImageFailure`) lives in
 * `src/agent/image-failure.ts` and imports `ImageFailure` from here —
 * agent → llm is the documented direction (CLAUDE.md → Module
 * Structure).
 */

import { AbortError } from "../util/with-retry.js";

/**
 * Discriminant matching `ImageProvider["kind"]` in
 * `src/llm/image-providers.ts`. Lives alongside the provider union so
 * adding a new image-provider type updates this set without cross-
 * layer churn.
 */
export type ImageProviderKind = "fal" | "oai" | "venice";

/**
 * Categorises an image-generation failure into one of a small set of
 * known shapes the LLM can react to.
 *
 * - `moderation_blocked` — provider's safety system flagged the prompt
 *   or the output (fal NSFW metadata, Venice content-violation header,
 *   gpt-image-1's `content_policy_violation`). LLM should rephrase or
 *   pick a different model.
 * - `blur_unexpected` — Venice returned a blurred image even though
 *   `safe_mode` was explicitly false. The operator opted out of blur,
 *   so getting one is a failed generation rather than a delivery
 *   target. LLM should treat as moderation.
 * - `placeholder_size` — the generated bytes are below the size canary
 *   in `src/agent/image-failure.ts`, implying the provider returned
 *   a solid-color or otherwise-degraded placeholder. LLM should retry
 *   or rephrase.
 * - `provider_error` — generic non-retryable upstream failure (4xx
 *   other than 429, bad keys, unknown model). LLM can sometimes route
 *   around by switching models.
 */
export type ImageFailureKind =
  | "moderation_blocked"
  | "blur_unexpected"
  | "placeholder_size"
  | "provider_error";

/**
 * Structured image-generation failure. `reason` is the LLM-facing
 * message; `kind` + `provider` are the structured fields operators
 * filter logs on.
 */
export interface ImageFailure {
  kind: ImageFailureKind;
  reason: string;
  provider: ImageProviderKind;
}

/**
 * Thrown by an adapter that detects a failure inline (Venice's
 * content-policy response headers). Extends `AbortError` so `withRetry`
 * treats it as fatal — every `ImageFailureKind` is non-retryable.
 *
 * The tool handler catches it inside the retried generation block and
 * returns `failure` as a value, then logs it and surfaces
 * `failure.reason` to the LLM. Consumers should switch on
 * `failure.kind` for behavior, not parse `message`.
 */
export class ImageGenerationFailedError extends AbortError {
  readonly failure: ImageFailure;

  constructor(failure: ImageFailure) {
    super(failure.reason);
    // AbortError pins `name: "AbortError"` as a literal type so a field
    // override at the class level won't compile; define it
    // imperatively on the instance for readable stack traces and
    // `error.name === "..."` log filtering. `instanceof AbortError`
    // still matches, which is what `p-retry` checks to stop.
    Object.defineProperty(this, "name", {
      value: "ImageGenerationFailedError",
      enumerable: false,
    });
    this.failure = failure;
  }
}
