/**
 * LiteLLM model catalog lookup.
 *
 * Two catalogs of the same shape, consulted in order:
 *
 *  1. **Live** — the newest `model_catalogs` row, fetched from upstream
 *     LiteLLM on a schedule (`src/agent/model-catalog/`) and installed here
 *     with {@link installLiveCatalog}: at boot, and after each refresh in the
 *     process that ran it. Absent until the first refresh lands.
 *  2. **Bundled** — `data/litellm-models.json`, regenerated by
 *     `scripts/refresh-litellm-models.ts` and shipped with each release.
 *     Covers a model the live catalog lacks: before the first refresh, one
 *     upstream has since retired, or an upstream that dropped entries.
 *
 * The resolver consults this layer when no explicit DB override exists for a
 * model id; each catalog covers a few thousand models across all major providers.
 *
 * The snapshot lives in `data/` (outside `src/rootDir`) so it stays a
 * data artefact rather than a TS module. We load it lazily via `fs` on
 * first lookup and cache for the process lifetime — ~20 ms one-shot cost
 * the first time `resolveLimits` runs, zero on every call after.
 *
 * ## Key normalization
 *
 * LiteLLM's keys are heterogeneous because the same upstream model id can
 * appear under multiple provider routings:
 *
 *  - `xai/grok-4.3` (xAI direct, what LiteLLM calls "xai")
 *  - `openrouter/x-ai/grok-4` (OpenRouter routing the same family)
 *  - `vertex_ai/xai/grok-4.20-reasoning` (Google Vertex hosting)
 *
 * Cogmo's model ids follow OpenRouter's `<org>/<model>` convention (`x-ai/`
 * with a hyphen, not `xai/`), so we try a small ladder of candidate keys
 * against the snapshot and return the first match. Order matters — the
 * exact key wins, then prefixed forms, then aliased forms.
 */
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { z } from "zod";

export interface LitellmEntry {
  contextWindow: number;
  maxOutputTokens: number;
}

export const LitellmEntrySchema = z.object({
  contextWindow: z.number().int().positive(),
  maxOutputTokens: z.number().int().positive(),
}) satisfies z.ZodType<LitellmEntry>;

/** Model id → limits, keyed the way LiteLLM keys its registry. */
export const LitellmCatalogSchema = z.record(z.string(), LitellmEntrySchema);

export type LitellmCatalog = Readonly<Record<string, LitellmEntry>>;

export interface LiveCatalog {
  entries: LitellmCatalog;
  fetchedAt: Date;
}

// Resolve from cwd, not relative to `import.meta.url`. tsup bundles this
// module into a top-level chunk in `dist/`, so the src→pkg depth (`../../`)
// doesn't survive the build — `import.meta.url`-relative resolution would
// look for `/data/...` instead of `/app/data/...` inside the container.
// Bootstrap already assumes cwd is the project root (cf. `loadHindsightCompat`
// in `src/boot/checks.ts`, `migrate(...)` reading `./migrations`); this
// stays consistent with that assumption. The Dockerfile's `WORKDIR /app`
// + `COPY data/ data/` puts the snapshot at the expected path.
const SNAPSHOT_PATH = resolve(process.cwd(), "data/litellm-models.json");

let cache: LitellmCatalog | null = null;
let live: LiveCatalog | null = null;

/** The bundled snapshot, loaded on first use. */
export function bundledSnapshot(): LitellmCatalog {
  if (cache) return cache;
  const body = readFileSync(SNAPSHOT_PATH, "utf-8");
  cache = LitellmCatalogSchema.parse(JSON.parse(body));
  return cache;
}

/**
 * Make `catalog` the live layer every later lookup in this process consults
 * ahead of the bundled snapshot. `null` leaves the bundled snapshot alone.
 */
export function installLiveCatalog(catalog: LiveCatalog | null): void {
  live = catalog;
}

/** When the live layer was fetched and how many ids it holds; `null` before one is installed. */
export function liveCatalogStatus(): { fetchedAt: Date; size: number } | null {
  return live && { fetchedAt: live.fetchedAt, size: Object.keys(live.entries).length };
}

/**
 * Look up a model id, returning its limits or `undefined`. Tries a ladder of
 * normalizations to bridge slug differences between cogmo's OpenRouter-style
 * ids and LiteLLM's per-provider keys. The whole ladder runs against the live
 * catalog before the bundled one, so a newer entry under any alias beats a
 * stale one under the exact id.
 */
export function lookupLitellm(modelId: string): LitellmEntry | undefined {
  const keys = candidateKeys(modelId);
  return (live && findFirst(live.entries, keys)) ?? findFirst(bundledSnapshot(), keys);
}

function findFirst(catalog: LitellmCatalog, keys: ReadonlyArray<string>): LitellmEntry | undefined {
  for (const key of keys) {
    const hit = catalog[key];
    if (hit) return hit;
  }
  return undefined;
}

/**
 * Generate the candidate lookup keys for a model id, in priority order.
 * Exported for tests; production callers go through {@link lookupLitellm}.
 *
 * Examples (input → candidates):
 *
 *  - `claude-sonnet-4-6` → [`claude-sonnet-4-6`]
 *  - `x-ai/grok-4.3` → [`x-ai/grok-4.3`, `openrouter/x-ai/grok-4.3`,
 *                       `xai/grok-4.3`, `grok-4.3`]
 *  - `openrouter/x-ai/grok-4.3` → [`openrouter/x-ai/grok-4.3`,
 *                                  `x-ai/grok-4.3`, `xai/grok-4.3`,
 *                                  `grok-4.3`]
 */
export function candidateKeys(modelId: string): string[] {
  const out: string[] = [modelId];

  // Strip a leading `openrouter/` if present, so `openrouter/x-ai/grok-4.3`
  // also tries `x-ai/grok-4.3`.
  if (modelId.startsWith("openrouter/")) {
    const stripped = modelId.slice("openrouter/".length);
    if (stripped) out.push(stripped);
  } else {
    // Otherwise, try with `openrouter/` prepended — LiteLLM publishes a
    // dedicated namespace for OpenRouter routings of the same family.
    out.push(`openrouter/${modelId}`);
  }

  // Cogmo uses OpenRouter's `x-ai/` (hyphen); LiteLLM (and the upstream
  // xAI direct API) use `xai/`. Bridge both directions.
  const aliased = aliasOrgPrefix(modelId);
  if (aliased && aliased !== modelId) {
    out.push(aliased);
    if (aliased.startsWith("openrouter/")) {
      const stripped = aliased.slice("openrouter/".length);
      if (stripped) out.push(stripped);
    } else {
      out.push(`openrouter/${aliased}`);
    }
  }

  // Last resort: keep only the last path segment and try the bare model
  // name. Catches the common case where LiteLLM keys the model under its
  // canonical (usually OpenAI/direct-vendor) namespace, regardless of how
  // many `<provider>/<org>/` layers cogmo's id wraps it in.
  const lastSlash = modelId.lastIndexOf("/");
  if (lastSlash >= 0) {
    const bare = modelId.slice(lastSlash + 1);
    if (bare) out.push(bare);
  }

  return [...new Set(out)];
}

/**
 * Map cogmo's `<org>/` prefix to LiteLLM's preferred form when they
 * differ. Returns null when no alias applies, so the caller can skip the
 * extra round of candidates.
 */
function aliasOrgPrefix(modelId: string): string | null {
  const aliases: ReadonlyArray<readonly [string, string]> = [
    ["x-ai/", "xai/"],
    ["openrouter/x-ai/", "openrouter/xai/"],
  ];
  for (const [from, to] of aliases) {
    if (modelId.startsWith(from)) {
      return to + modelId.slice(from.length);
    }
  }
  return null;
}
