packages:
  - "."

injectWorkspacePackages: true

allowBuilds:
  cpu-features: false
  esbuild: false
  protobufjs: false
  ssh2: false

overrides:
  "ip-address@<10.1.1": ">=10.1.1"
  "qs@<6.15.2": ">=6.15.2"
  "@opentelemetry/otlp-transformer@0.217.0": "^0.218.0"

patchedDependencies:
  '@daytonaio/sdk@0.175.0': patches/@daytonaio__sdk@0.175.0.patch
