/**
 * Image-generation failure types and detection.
 *
 * Two surfaces converge here:
 *
 * 1. `detectImageFailure` — post-generation inspection that runs against
 *    the AI SDK's `generateImage` result. Catches signals the SDK
 *    doesn't surface as errors (fal's per-image NSFW flag in
 *    `providerMetadata`, the cross-provider size canary).
 *
 * 2. `ImageGenerationFailedError` — thrown by adapters whose protocol
 *    surfaces failure signals as inline response data, not as
 *    SDK-emitted errors. Today: Venice's response-header censorship
 *    signals; openai-compat's moderation-flavored 4xx responses
 *    (gpt-image-1's `content_policy_violation`) get converted in the
 *    tool handler.
 *
 * Both produce the same `ImageFailure` value at the tool boundary, so
 * the LLM gets a uniform error shape regardless of which surface
 * detected the failure.
 */

import type { GenerateImageResult } from "ai";
import { z } from "zod";
import { AbortError } from "../util/with-retry.js";

/**
 * Generated images whose byte length falls below this threshold are treated
 * as provider placeholders (solid-color / heavily-degraded fallbacks that
 * compress to a few hundred bytes). Real PNG/JPEG/WebP photos from a
 * diffusion model are 50KB+ even at modest resolution; a 2KB ceiling
 * comfortably catches the placeholder class without false-positiving on
 * legitimate small assets (transparent 1x1 stubs in tests are explicitly
 * excluded via the test fixture, which produces ~400B images — those
 * intentionally trip the canary so tests assert on the failure path).
 *
 * Starting point — tune from production data if false positives appear.
 */
export const SUSPICIOUS_SIZE_THRESHOLD_BYTES = 2048;

/**
 * Discriminant matching `ImageProvider["kind"]` in
 * `src/llm/image-providers.ts`. Detection rules branch on this; the
 * value also rides on every `ImageFailure` so log/error consumers
 * can filter by provider.
 */
export type ImageProviderKind = "fal" | "oai" | "venice";

/**
 * Categorises an image-generation failure into one of a small set of
 * known shapes the LLM can react to.
 *
 * - `moderation_blocked` — provider's safety system flagged the prompt
 *   or the output (fal NSFW metadata, Venice content-violation header,
 *   gpt-image-1's `content_policy_violation`). LLM should rephrase or
 *   pick a different model.
 * - `blur_unexpected` — Venice returned a blurred image even though
 *   `safe_mode` was explicitly false. The operator opted out of blur,
 *   so getting one is a failed generation rather than a delivery
 *   target. LLM should treat as moderation.
 * - `placeholder_size` — the generated bytes are below the size canary
 *   (`SUSPICIOUS_SIZE_THRESHOLD_BYTES`), implying the provider returned
 *   a solid-color or otherwise-degraded placeholder. LLM should retry
 *   or rephrase.
 * - `provider_error` — generic non-retryable upstream failure (4xx
 *   other than 429, bad keys, unknown model). LLM can sometimes route
 *   around by switching models.
 */
export type ImageFailureKind =
  | "moderation_blocked"
  | "blur_unexpected"
  | "placeholder_size"
  | "provider_error";

/**
 * Structured image-generation failure. `reason` is the LLM-facing
 * message; `kind` + `provider` are the structured fields operators
 * filter logs on.
 */
export interface ImageFailure {
  kind: ImageFailureKind;
  reason: string;
  provider: ImageProviderKind;
}

/**
 * Thrown by adapters that detect failure inline (Venice's response
 * headers, the tool handler's APICallError conversion for
 * openai-compat moderation). Extends `AbortError` so `withRetry`
 * treats it as fatal — every `ImageFailureKind` is non-retryable.
 *
 * The tool handler catches this once at the call site, logs the
 * structured `failure`, and surfaces `failure.reason` to the LLM.
 * Consumers should switch on `failure.kind` for behavior, not parse
 * `message`.
 */
export class ImageGenerationFailedError extends AbortError {
  readonly failure: ImageFailure;

  constructor(failure: ImageFailure) {
    super(failure.reason);
    // AbortError pins `name: "AbortError"` as a literal type so a field
    // override at the class level won't compile; define it
    // imperatively on the instance for readable stack traces and
    // `error.name === "..."` log filtering. `instanceof AbortError`
    // still matches, which is what `p-retry` checks to stop.
    Object.defineProperty(this, "name", {
      value: "ImageGenerationFailedError",
      enumerable: false,
    });
    this.failure = failure;
  }
}

/**
 * Result of inspecting a successful `generateImage` response. `ok: false`
 * carries a structured `failure` the tool surfaces uniformly with the
 * thrown-path failures, so the LLM sees one shape regardless of which
 * surface produced the failure.
 */
export type ImageFailureDetection = { ok: true } | { ok: false; failure: ImageFailure };

/**
 * Per-image NSFW flag the fal adapter normalizes from upstream `has_nsfw_concepts[i]`
 * / `nsfw_content_detected[i]` into `providerMetadata.fal.images[i].nsfw`.
 * Optional — fal returns it only when the model's safety checker runs.
 */
const FalImageMetaSchema = z
  .object({
    nsfw: z.boolean().optional(),
  })
  .passthrough();

/**
 * Slice of fal's `providerMetadata.fal` we care about. The SDK passes
 * unknown response fields through verbatim (`...responseMetaData`), so
 * `nsfw_concepts: string[]` may appear at the top level of the slice if
 * the upstream response carries it — `.passthrough()` keeps it
 * accessible without forcing every fixture to set it.
 *
 * `nsfw_concepts` is **response-level**, not per-image — fal returns a
 * single concept list for the whole batch with no per-image attribution.
 * When a multi-image response has only some images flagged, the reason
 * string still attaches the full concept list to the user-visible
 * message. Acceptable today (the LLM acts on the prompt, not on which
 * specific image tripped); revisit if fal exposes per-image concepts.
 */
const FalProviderMetaSchema = z
  .object({
    images: z.array(FalImageMetaSchema).optional(),
    nsfw_concepts: z.array(z.string()).optional(),
  })
  .passthrough();

/**
 * Inspect a successful `generateImage` result for known failure signals.
 *
 * Checks run in order of specificity: provider-specific metadata first
 * (fal's per-image NSFW flag), then the cross-provider size canary. The
 * first failure short-circuits — a flagged-and-tiny image still reports
 * the NSFW reason because that's the more actionable hint for the LLM.
 *
 * No pixel decode. The cheap signals catch the placeholder class; an
 * image-processing dep is deferred until production traffic shows a
 * real case the signals miss.
 */
export function detectImageFailure(input: {
  /**
   * Only the byte length is consumed; widen the input type to anything
   * carrying a `Uint8Array` so non-AI-SDK adapters (e.g. venice's hand-
   * rolled output) can pass their bytes directly without a synthetic
   * `base64` field.
   */
  image: { uint8Array: Uint8Array };
  providerMetadata: GenerateImageResult["providerMetadata"] | undefined;
  providerKind: ImageProviderKind;
}): ImageFailureDetection {
  if (input.providerKind === "fal") {
    const parsed = FalProviderMetaSchema.safeParse(input.providerMetadata?.fal);
    if (parsed.success) {
      const flagged = parsed.data.images?.some((img) => img.nsfw === true) ?? false;
      if (flagged) {
        const concepts = parsed.data.nsfw_concepts ?? [];
        const conceptHint = concepts.length > 0 ? ` (concepts: ${concepts.join(", ")})` : "";
        return {
          ok: false,
          failure: {
            kind: "moderation_blocked",
            provider: "fal",
            reason:
              `image was flagged as nsfw by fal${conceptHint}. ` +
              "The provider returned a placeholder instead of the requested image — " +
              "rephrase the prompt to avoid the flagged content, or pick a different model.",
          },
        };
      }
    }
  }

  const byteLength = input.image.uint8Array.byteLength;
  if (byteLength < SUSPICIOUS_SIZE_THRESHOLD_BYTES) {
    return {
      ok: false,
      failure: {
        kind: "placeholder_size",
        provider: input.providerKind,
        reason:
          `generated image is suspiciously small (${byteLength} bytes), likely a placeholder. ` +
          "The provider may have refused the prompt — try rephrasing or switching models.",
      },
    };
  }

  return { ok: true };
}
