import { RequestError } from "@octokit/request-error";
import type { Octokit } from "@octokit/rest";
import { describe, expect, it, vi } from "vitest";
import { buildBody, parseRemoteUrl, runOpenDraftPr, truncateTitle } from "./draft-pr.js";

function fakeOctokit(create: ReturnType<typeof vi.fn>): Octokit {
  return { pulls: { create } } as unknown as Octokit;
}

function requestError(status: number, message: string): RequestError {
  // RequestError requires a request object; the fields the runner reads
  // are `status` + `message`. Construct a minimal instance.
  return new RequestError(message, status, {
    request: {
      method: "POST",
      url: "https://api.github.com/repos/o/r/pulls",
      headers: {},
    },
    response: {
      status,
      url: "https://api.github.com/repos/o/r/pulls",
      headers: {},
      data: { message },
    },
  });
}

describe("parseRemoteUrl", () => {
  it.each([
    ["git@github.com:owner/repo.git", { owner: "owner", repo: "repo" }],
    ["git@github.com:owner/repo", { owner: "owner", repo: "repo" }],
    ["https://github.com/owner/repo.git", { owner: "owner", repo: "repo" }],
    ["https://github.com/owner/repo", { owner: "owner", repo: "repo" }],
    ["ssh://git@github.com/owner/repo.git", { owner: "owner", repo: "repo" }],
    [
      "https://github.com/org-with-dash/repo.with-dot.git",
      { owner: "org-with-dash", repo: "repo.with-dot" },
    ],
  ])("parses %s", (url, expected) => {
    expect(parseRemoteUrl(url)).toEqual(expected);
  });

  it.each([
    "",
    "not-a-url",
    "git@github.com:onlyone",
    "https://github.com/onlyone",
    "https://github.com/",
  ])("returns null for unparseable %s", (url) => {
    expect(parseRemoteUrl(url)).toBeNull();
  });
});

describe("truncateTitle", () => {
  it("collapses whitespace and trims", () => {
    expect(truncateTitle("  hello  world\n\nlines  ")).toBe("hello world lines");
  });

  it("returns the goal verbatim when within budget", () => {
    expect(truncateTitle("short goal")).toBe("short goal");
  });

  it("truncates with an ellipsis at 70 chars", () => {
    const long = "x".repeat(100);
    const out = truncateTitle(long);
    expect(out.length).toBe(70);
    expect(out.endsWith("…")).toBe(true);
  });
});

describe("buildBody", () => {
  it("includes plan, fenced verify output, and the Cogmo footer", () => {
    const body = buildBody({
      plan: "1. step one\n2. step two",
      verifyOutput: "PASS\n  ok",
    });
    expect(body).toContain("## Plan");
    expect(body).toContain("1. step one");
    expect(body).toContain("## Verify output");
    expect(body).toMatch(/```\nPASS\n {2}ok\n```/);
    expect(body).toContain("_Generated by Cogmo_");
  });

  it("falls back to placeholders when plan or verify is empty", () => {
    const body = buildBody({ plan: "   ", verifyOutput: "" });
    expect(body).toContain("_(no plan recorded)_");
    expect(body).toContain("_(no output)_");
  });

  it("widens the fence past any backtick run in the verify output", () => {
    // Verify output contains a 3-backtick run (a literal markdown fence).
    // The wrapping fence must be >=4 backticks or the inner ``` would close
    // the outer fence prematurely and leak the rest of the body as raw text.
    const body = buildBody({
      plan: "p",
      verifyOutput: "before\n```\nfence inside\n```\nafter",
    });
    expect(body).toMatch(/\n````\nbefore\n```\nfence inside\n```\nafter\n````\n/);
  });

  it("widens further when the inner content contains 4+ backticks", () => {
    const body = buildBody({
      plan: "p",
      verifyOutput: "````\ndeep\n````",
    });
    // Outer fence must be at least 5 backticks.
    expect(body).toMatch(/\n`````\n````\ndeep\n````\n`````\n/);
  });
});

const BASE_PARAMS = {
  pat: "ghp_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  owner: "user",
  repo: "cogmo",
  head: "cogmo/abc12345",
  base: "main",
  goal: "test goal",
  plan: "1. step one",
  verifyOutput: "PASS",
  branchSha: "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
};

describe("runOpenDraftPr", () => {
  it("calls pulls.create with draft=true and returns kind=opened", async () => {
    const create = vi.fn(async () => ({
      data: {
        html_url: "https://github.com/user/cogmo/pull/42",
        number: 42,
      },
    }));
    const result = await runOpenDraftPr({
      ...BASE_PARAMS,
      octokit: fakeOctokit(create),
    });

    expect(create).toHaveBeenCalledWith({
      owner: "user",
      repo: "cogmo",
      title: "test goal",
      head: "cogmo/abc12345",
      base: "main",
      body: expect.stringContaining("## Plan"),
      draft: true,
    });
    expect(result.kind).toBe("opened");
    if (result.kind === "opened") {
      expect(result.url).toBe("https://github.com/user/cogmo/pull/42");
      expect(result.number).toBe(42);
      expect(result.branchSha).toBe(BASE_PARAMS.branchSha);
      expect(new Date(result.openedAt).toString()).not.toBe("Invalid Date");
    }
  });

  it("maps 401 to kind=auth_failed", async () => {
    const create = vi.fn(async () => {
      throw requestError(401, "Bad credentials");
    });
    const result = await runOpenDraftPr({
      ...BASE_PARAMS,
      octokit: fakeOctokit(create),
    });
    expect(result.kind).toBe("auth_failed");
    if (result.kind === "auth_failed") expect(result.status).toBe(401);
  });

  it("maps 403 to kind=auth_failed", async () => {
    const create = vi.fn(async () => {
      throw requestError(403, "Resource not accessible by integration");
    });
    const result = await runOpenDraftPr({
      ...BASE_PARAMS,
      octokit: fakeOctokit(create),
    });
    expect(result.kind).toBe("auth_failed");
  });

  it("maps 422 to kind=validation_failed (e.g. PR already exists)", async () => {
    const create = vi.fn(async () => {
      throw requestError(422, "A pull request already exists for cogmo/abc12345");
    });
    const result = await runOpenDraftPr({
      ...BASE_PARAMS,
      octokit: fakeOctokit(create),
    });
    expect(result.kind).toBe("validation_failed");
    if (result.kind === "validation_failed") {
      expect(result.message).toMatch(/already exists/);
    }
  });

  it("maps non-RequestError throwables to kind=failed", async () => {
    const create = vi.fn(async () => {
      throw new Error("ETIMEDOUT");
    });
    const result = await runOpenDraftPr({
      ...BASE_PARAMS,
      octokit: fakeOctokit(create),
    });
    expect(result.kind).toBe("failed");
    if (result.kind === "failed") expect(result.message).toContain("ETIMEDOUT");
  });

  it("maps unrecognised RequestError statuses to kind=failed with the status code", async () => {
    const create = vi.fn(async () => {
      throw requestError(500, "Server Error");
    });
    const result = await runOpenDraftPr({
      ...BASE_PARAMS,
      octokit: fakeOctokit(create),
    });
    expect(result.kind).toBe("failed");
    if (result.kind === "failed") expect(result.message).toContain("500");
  });

  it("truncates a long goal in the title", async () => {
    const create = vi.fn(async () => ({
      data: { html_url: "https://github.com/x/y/pull/1", number: 1 },
    }));
    await runOpenDraftPr({
      ...BASE_PARAMS,
      goal: "x".repeat(200),
      octokit: fakeOctokit(create),
    });
    const callArg = create.mock.calls[0]?.[0] as { title: string };
    expect(callArg.title.length).toBe(70);
    expect(callArg.title.endsWith("…")).toBe(true);
  });
});
