import { createHash } from "node:crypto";
import { err, ok, type Result } from "neverthrow";
import { GitOpsError, gitShow } from "./git-ops.js";

/**
 * Filename for the hash-pinned lockfile committed alongside `skill.py`.
 * Generated by `uv pip compile --generate-hashes` against the manifest's
 * `dependencies`. See `design/skills.md` → Dependencies.
 */
export const REQUIREMENTS_LOCK_FILE = "requirements.lock";

export interface LockfileSnapshot {
  /** sha256 over the lockfile contents (UTF-8 bytes). */
  hash: string;
  /** Raw lockfile text. The dependency populator (PR2) feeds this to `uv pip sync`. */
  contents: string;
}

export type LockfileReadError =
  | { kind: "missing"; message: string }
  | { kind: "empty"; message: string };

/**
 * Read `requirements.lock` at the given commit and snapshot it. Caller
 * decides whether the file is required based on `manifest.dependencies` —
 * an empty dependency list means no lockfile, no hash, populator skipped.
 *
 * Returns:
 *   - `ok(LockfileSnapshot)` when the file is present and non-empty.
 *   - `err({ kind: "missing" })` when git reports `file_not_found`.
 *   - `err({ kind: "empty" })` when the file is present but blank.
 *
 * Other git failures (unreadable repo, missing sha) propagate as thrown
 * `GitOpsError`s — they indicate infrastructure-level bugs, not author
 * mistakes the register flow can surface as `errors[]`.
 */
export async function readLockfileAtSha(
  repoPath: string,
  gitSha: string,
): Promise<Result<LockfileSnapshot, LockfileReadError>> {
  let contents: string;
  try {
    contents = await gitShow(repoPath, gitSha, REQUIREMENTS_LOCK_FILE);
  } catch (e) {
    if (e instanceof GitOpsError && e.code === "file_not_found") {
      return err({
        kind: "missing",
        message: `${REQUIREMENTS_LOCK_FILE} not found at ${gitSha}`,
      });
    }
    throw e;
  }
  if (contents.trim().length === 0) {
    return err({
      kind: "empty",
      message: `${REQUIREMENTS_LOCK_FILE} is empty at ${gitSha}`,
    });
  }
  return ok({
    hash: createHash("sha256").update(contents, "utf-8").digest("hex"),
    contents,
  });
}
