/**
 * PR runner — slice 4.0g.
 *
 * Calls `POST /repos/{owner}/{repo}/pulls` via `@octokit/rest`. The PR
 * opens ready for review, not as a draft: PR creation is already gated
 * on the verify step passing, the human-approval gate is the merge
 * itself, and at single-user scale the draft state adds a manual
 * "ready for review" click without guarding anything. Ready PRs also
 * work on plans where drafts are unavailable and play well with
 * review-request automation.
 *
 * Owner/repo are parsed from `coding_repos.remote_url`
 * (handles both `git@github.com:owner/repo.git` and
 * `https://github.com/owner/repo.git`). Returns a discriminated result
 * so the orchestrator can render the right Telegram message and persist
 * the right `failure_reason`.
 *
 * Title: `task.goal` truncated to 70 chars (no prefix).
 * Body: markdown — `## Plan\n\n<plan>\n\n## Verify output\n\n` + fenced
 * verify output + `_Generated by Cogmo_` footer. The verbatim plan keeps
 * the body stable and useful; LLM-summarised bodies are deferred.
 */

import { RequestError } from "@octokit/request-error";
import { Octokit } from "@octokit/rest";

const TITLE_MAX_CHARS = 70;
const BODY_PLAN_HEADER = "## Plan";
const BODY_VERIFY_HEADER = "## Verify output";
const BODY_FOOTER = "_Generated by Cogmo_";

export interface OpenPrParams {
  /** Bot account PAT — from the resolved `github_identity:<name>` bundle. */
  pat: string;
  /** `owner/repo` — parsed from `coding_repos.remote_url` upstream. */
  owner: string;
  repo: string;
  /** Branch already pushed by the commit-and-push step (4.0f). */
  head: string;
  /** Default branch — `coding_repos.default_branch`, typically `main`. */
  base: string;
  /** Verbatim task goal — used as the PR title (truncated). */
  goal: string;
  /** Plan text from the plan phase. May be empty when planning was skipped. */
  plan: string;
  /** Verify output captured by 4.0e — included verbatim under a fenced block. */
  verifyOutput: string;
  /** Commit SHA pushed by 4.0f — recorded into `pr_metadata.branchSha`. */
  branchSha: string;
  /** Optional Octokit instance — tests inject a mock; production lets us construct one. */
  octokit?: Octokit;
}

export type OpenPrResult =
  | {
      kind: "opened";
      url: string;
      number: number;
      branchSha: string;
      openedAt: string;
    }
  | { kind: "auth_failed"; status: number; message: string }
  | { kind: "validation_failed"; status: number; message: string }
  | { kind: "failed"; message: string };

/**
 * Parse `owner/repo` out of a git remote URL.
 *
 * Accepts:
 *   git@github.com:owner/repo.git
 *   git@github.com:owner/repo
 *   https://github.com/owner/repo.git
 *   https://github.com/owner/repo
 *   ssh://git@github.com/owner/repo.git
 */
export function parseRemoteUrl(remoteUrl: string): { owner: string; repo: string } | null {
  // SSH form: git@host:owner/repo(.git)?
  const sshScp = /^[^@\s]+@[^:\s]+:(?<owner>[^/\s]+)\/(?<repo>[^/\s]+?)(?:\.git)?$/.exec(remoteUrl);
  const owner = sshScp?.groups?.owner;
  const repo = sshScp?.groups?.repo;
  if (owner && repo) {
    return { owner, repo };
  }

  // ssh:// or https:// form. URL parser handles both.
  try {
    const u = new URL(remoteUrl);
    const segments = u.pathname.replace(/^\/+/, "").split("/");
    if (segments.length >= 2 && segments[0] && segments[1]) {
      const repo = segments[1].replace(/\.git$/, "");
      if (repo) return { owner: segments[0], repo };
    }
  } catch {
    // not a URL — fall through
  }
  return null;
}

export function truncateTitle(goal: string): string {
  // Single-line + byte-cap. `task.goal` is freeform; collapse newlines to
  // spaces so the PR title doesn't render multiline on GitHub.
  const flat = goal.replace(/\s+/g, " ").trim();
  if (flat.length <= TITLE_MAX_CHARS) return flat;
  return `${flat.slice(0, TITLE_MAX_CHARS - 1)}…`;
}

export function buildBody(params: { plan: string; verifyOutput: string }): string {
  const plan = params.plan.trim() || "_(no plan recorded)_";
  const verify = params.verifyOutput.trim() || "_(no output)_";
  // CommonMark closes a fenced block on a line whose backtick run is at
  // least as long as the opening fence. Pick a fence that's strictly
  // longer than any backtick run inside the body so verify output
  // containing literal triple-backticks (markdown rendered docs in test
  // output, etc.) doesn't truncate the fence early.
  const fence = "`".repeat(Math.max(3, longestBacktickRun(verify) + 1));
  return [
    BODY_PLAN_HEADER,
    "",
    plan,
    "",
    BODY_VERIFY_HEADER,
    "",
    fence,
    verify,
    fence,
    "",
    BODY_FOOTER,
    "",
  ].join("\n");
}

/** Length of the longest run of consecutive backticks in `s`. */
function longestBacktickRun(s: string): number {
  let max = 0;
  let cur = 0;
  for (const ch of s) {
    if (ch === "`") {
      cur += 1;
      if (cur > max) max = cur;
    } else {
      cur = 0;
    }
  }
  return max;
}

export async function runOpenPr(params: OpenPrParams): Promise<OpenPrResult> {
  const octokit = params.octokit ?? new Octokit({ auth: params.pat });

  const title = truncateTitle(params.goal);
  const body = buildBody({ plan: params.plan, verifyOutput: params.verifyOutput });

  try {
    const response = await octokit.pulls.create({
      owner: params.owner,
      repo: params.repo,
      title,
      head: params.head,
      base: params.base,
      body,
    });
    return {
      kind: "opened",
      url: response.data.html_url,
      number: response.data.number,
      branchSha: params.branchSha,
      openedAt: new Date().toISOString(),
    };
  } catch (error) {
    if (error instanceof RequestError) {
      if (error.status === 401 || error.status === 403) {
        return { kind: "auth_failed", status: error.status, message: error.message };
      }
      if (error.status === 422) {
        // Validation failure — most commonly "A pull request already exists
        // for <branch>" or "Head sha does not exist". Surface the message
        // so the orchestrator's failure_reason carries it verbatim.
        return { kind: "validation_failed", status: error.status, message: error.message };
      }
      return { kind: "failed", message: `${error.status} ${error.message}` };
    }
    return { kind: "failed", message: (error as Error).message };
  }
}
