/**
 * GitHub identity bundle — stored as one row in the secrets table under
 * `github_identity:<name>`, value is a JSON-encoded `{ pat, sshPrivateKey,
 * sshPublicKey }`. The PAT authenticates HTTPS git pushes (via `GIT_ASKPASS`)
 * and the GitHub REST API; the SSH keypair signs commits (`gpg.format=ssh` +
 * `user.signingkey`). PAT and signing key live together because they belong
 * to the same bot account — half-set is invalid; either the identity is
 * provisioned (all three present) or it isn't.
 *
 * Multiple identities are supported via the name suffix: `github_identity:default`
 * is the wizard-created identity, additional identities can be installed
 * out-of-band and selected per repo via `coding_repos.identity_name`.
 */

import { err, ok, type Result } from "neverthrow";
import { z } from "zod";

export const GitHubIdentitySchema = z
  .object({
    /** Fine-grained personal access token. Authorises repo contents + pull
     * request scopes for every repo this identity touches. */
    pat: z.string().min(1),
    /** OpenSSH-formatted Ed25519 private key. Generated by the setup wizard
     * and never leaves the encrypted DB except to be written to the
     * per-task askpass directory at task start (slice 4.0d). */
    sshPrivateKey: z.string().min(1),
    /** OpenSSH-formatted Ed25519 public key. Stored alongside the private
     * key for fingerprint display and re-export to the user when they need
     * to re-add it as a signing key on github.com. */
    sshPublicKey: z.string().min(1),
    /** GitHub username. Captured by `validateGitHubPat` against
     * `GET /user` at setup time. Used to compose the canonical noreply
     * commit author email (`<id>+<login>@users.noreply.github.com`),
     * which matches the bot account so PRs render the right avatar.
     *
     * Optional for backwards-compatibility: identities provisioned before
     * the canonical-author change (slice 4.0i follow-up) lack this field.
     * Consumers fall back to a generic noreply email when absent and a
     * subsequent `cogmo setup` re-run augments the bundle with the
     * captured login + id. */
    login: z.string().min(1).optional(),
    /** GitHub numeric user id. Captured alongside `login` from `GET /user`.
     * Stored as a string so JSON round-trips losslessly across any
     * downstream that parses through 32-bit numerics. Optional for the
     * same backwards-compatibility reason as `login`. */
    id: z.string().regex(/^\d+$/, "expected numeric GitHub user id").optional(),
  })
  .strict();
export type GitHubIdentity = z.infer<typeof GitHubIdentitySchema>;

export const DEFAULT_GITHUB_IDENTITY_NAME = "default";

const SECRET_NAME_PREFIX = "github_identity:";

/** Build the secrets-table key for a named GitHub identity. */
export function gitHubIdentitySecretName(name: string): string {
  return `${SECRET_NAME_PREFIX}${name}`;
}

export type ResolveIdentityError =
  | { code: "missing"; identityName: string }
  | { code: "malformed_json"; identityName: string }
  | { code: "schema_mismatch"; identityName: string; issues: z.core.$ZodIssue[] };

/** Minimal interface required to look up a stored identity bundle. Defined
 * locally rather than importing `SecretsStore` directly so this module stays
 * dependency-light — any object that can fetch a secret by name fits. */
export interface GitHubIdentitySecretsLookup {
  getSecret(name: string): Promise<string | null>;
}

/**
 * Look up and validate a GitHub identity by name.
 *
 * Errors:
 * - `missing`: no row in the secrets table — the wizard hasn't installed
 *   this identity yet.
 * - `malformed_json`: row exists but the decrypted plaintext isn't JSON.
 *   Indicates corruption or a hand-edited DB.
 * - `schema_mismatch`: row decoded as JSON but didn't pass `GitHubIdentitySchema`
 *   (e.g. missing `sshPrivateKey`). Same root cause as `malformed_json`.
 */
export async function resolveGitHubIdentity(
  secrets: GitHubIdentitySecretsLookup,
  identityName: string,
): Promise<Result<GitHubIdentity, ResolveIdentityError>> {
  const raw = await secrets.getSecret(gitHubIdentitySecretName(identityName));
  if (raw === null) return err({ code: "missing", identityName });

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return err({ code: "malformed_json", identityName });
  }

  const result = GitHubIdentitySchema.safeParse(parsed);
  if (!result.success) {
    return err({ code: "schema_mismatch", identityName, issues: result.error.issues });
  }
  return ok(result.data);
}

/** Convenience wrapper: looks up the identity for a given repo row. */
export function resolveGitHubIdentityForRepo(
  secrets: GitHubIdentitySecretsLookup,
  repo: { identityName: string },
): Promise<Result<GitHubIdentity, ResolveIdentityError>> {
  return resolveGitHubIdentity(secrets, repo.identityName);
}

/** Serialise an identity bundle for storage. The store handles encryption. */
export function serializeGitHubIdentity(identity: GitHubIdentity): string {
  return JSON.stringify(GitHubIdentitySchema.parse(identity));
}

/** Human-readable error message for surfacing to the operator (Telegram, logs). */
export function describeResolveIdentityError(error: ResolveIdentityError): string {
  switch (error.code) {
    case "missing":
      return `GitHub identity '${error.identityName}' is not configured. Run the setup wizard (or set COGMO_GITHUB_PAT for non-interactive setup) to install it.`;
    case "malformed_json":
      return `GitHub identity '${error.identityName}' is corrupt: stored value is not valid JSON.`;
    case "schema_mismatch":
      return `GitHub identity '${error.identityName}' is malformed: ${error.issues.map((i) => i.message).join("; ")}.`;
  }
}
