#!/usr/bin/env tsx
/**
 * Run tokei with autogenerated files excluded.
 *
 * Source of truth: `.gitattributes` entries marked `linguist-generated=true`.
 * Each matching pattern becomes a `--exclude` flag, so tokei stays in sync
 * with what GitHub treats as generated — no separate `.tokeignore` to drift.
 */
import { spawnSync } from "node:child_process";
import { readFileSync } from "node:fs";

function generatedPatterns(): string[] {
  const lines = readFileSync(".gitattributes", "utf8").split("\n");
  return lines.flatMap((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return [];
    const tokens = trimmed.split(/\s+/);
    if (!tokens.slice(1).includes("linguist-generated=true")) return [];
    return [tokens[0]];
  });
}

const excludes = generatedPatterns().flatMap((p) => ["--exclude", p]);
const result = spawnSync("tokei", [...excludes, ...process.argv.slice(2)], {
  stdio: "inherit",
});
process.exit(result.status ?? 1);
